//HintName: MyString32.g.cs
// <auto-generated />
#nullable enable
namespace TestNs
{
    [global::System.Runtime.InteropServices.StructLayout(global::System.Runtime.InteropServices.LayoutKind.Explicit)]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SampSharp.SourceGenerator", "1.0.0.0")]
    public readonly struct MyString32
    {
        private const int Size = 32;
        public MyString32(int value)
        {
            Value = value;
        }

        public readonly int Value;
    }
}