//HintName: MyString24.g.cs
// <auto-generated />
#nullable enable
namespace TestNs
{
    [global::System.Runtime.InteropServices.StructLayout(global::System.Runtime.InteropServices.LayoutKind.Explicit)]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SampSharp.SourceGenerator", "0.0.0.0")]
    public readonly struct MyString24
    {
        private const int Size = 24;
        public MyString24(int value)
        {
            Value = value;
        }

        public readonly int Value;
    }
}