//HintName: ITestApi.g.cs
// <auto-generated />
#nullable enable
namespace TestApi
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SampSharp.SourceGenerator", "1.0.0.0")]
    [global::System.Runtime.CompilerServices.SkipLocalsInitAttribute]
    public readonly unsafe partial struct ITestApi : global::System.IEquatable<ITestApi>, global::TestApi.ITestApi.IManagedInterface
    {
        private readonly nint _handle;
        /// <summary>Initializes a new instance of the <see cref = "ITestApi"/> struct.</summary>
        /// <param name="handle">A pointer to the unmanaged interface.</param>
        public ITestApi(nint handle)
        {
            _handle = handle;
        }

        /// <inheritdoc/>
        public nint Handle => _handle;
        /// <inheritdoc/>
        public readonly bool HasValue => _handle != default;

        /// <inheritdoc/>
        public override int GetHashCode()
        {
            return _handle.GetHashCode();
        }

        /// <inheritdoc/>
        public bool Equals(ITestApi other)
        {
            return _handle == other._handle;
        }

        /// <inheritdoc/>
        public override bool Equals(object? other)
        {
            if (_handle == default)
                return other == null;
            if (other == null)
                return false;
            if (other is ITestApi otherValue)
            {
                return Equals(otherValue);
            }

            return false;
        }

        /// <summary>Determines whether the specified values are equal.</summary>
        /// <param name="lhs">The value on the left side of the operator.</param>
        /// <param name="rhs">The value on the right side of the operator.</param>
        /// <returns><c>true</c> if the values are equal; otherwise, <c>false</c>.</returns>
        public static bool operator ==(ITestApi lhs, object? rhs)
        {
            if (rhs is null)
                return !lhs.HasValue;
            if (rhs is ITestApi other)
                return lhs.Equals(other);
            return false;
        }

        /// <summary>Determines whether the specified values are not equal.</summary>
        /// <param name="lhs">The value on the left side of the operator.</param>
        /// <param name="rhs">The value on the right side of the operator.</param>
        /// <returns><c>true</c> if the values are not equal; otherwise, <c>false</c>.</returns>
        public static bool operator !=(ITestApi lhs, object? rhs) => !(lhs == rhs);
        public partial int GetId()
        {
            return __PInvoke(_handle);
            // Local P/Invoke
            [global::System.Runtime.InteropServices.DllImportAttribute("SampSharp", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl, EntryPoint = "ITestApi_getId", ExactSpelling = true)]
            static unsafe extern int __PInvoke(nint handle_);
        }

        public partial void SetName(string name)
        {
            global::SampSharp.OpenMp.Core.Std.StringView __name_native = default;
            // Setup - Perform required setup.
            scoped global::SampSharp.OpenMp.Core.Std.StringViewMarshaller.ManagedToNative __name_native__marshaller = new();
            try
            {
                // Marshal - Convert managed data to native data.
                global::System.Span<byte> __name_native__buffer = stackalloc byte[global::SampSharp.OpenMp.Core.Std.StringViewMarshaller.ManagedToNative.BufferSize];
                __name_native__marshaller.FromManaged(name, __name_native__buffer);
                {
                    // PinnedMarshal - Convert managed data to native data that requires the managed data to be pinned.
                    __name_native = __name_native__marshaller.ToUnmanaged();
                    __PInvoke(_handle, __name_native);
                }
            }
            finally
            {
                // CleanupCallerAllocated - Perform cleanup of caller allocated resources.
                __name_native__marshaller.Free();
            }

            // Local P/Invoke
            [global::System.Runtime.InteropServices.DllImportAttribute("SampSharp", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl, EntryPoint = "ITestApi_setName", ExactSpelling = true)]
            static unsafe extern void __PInvoke(nint handle_, global::SampSharp.OpenMp.Core.Std.StringView name);
        }

        public partial bool IsActive()
        {
            bool __retVal = default;
            global::SampSharp.OpenMp.Core.BlittableBoolean __retVal_native = default;
            {
                __retVal_native = __PInvoke(_handle);
            }

            // Unmarshal - Convert native data to managed data.
            __retVal = global::SampSharp.OpenMp.Core.Std.BooleanMarshaller.NativeToManaged.ConvertToManaged(__retVal_native)!;
            return __retVal;
            // Local P/Invoke
            [global::System.Runtime.InteropServices.DllImportAttribute("SampSharp", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl, EntryPoint = "ITestApi_isActive", ExactSpelling = true)]
            static unsafe extern global::SampSharp.OpenMp.Core.BlittableBoolean __PInvoke(nint handle_);
        }

        /// <summary>Represents the managed interface implemented by its unmanaged counterpart.</summary>
        public partial interface IManagedInterface : global::SampSharp.OpenMp.Core.IUnmanagedInterface
        {
            public int GetId();
            public void SetName(string name);
            public bool IsActive();
        }
    }
}