//HintName: IOverloadApi.g.cs
// <auto-generated />
#nullable enable
namespace TestApi
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SampSharp.SourceGenerator", "0.0.0.0")]
    [global::System.Runtime.CompilerServices.SkipLocalsInitAttribute]
    public readonly unsafe partial struct IOverloadApi : global::System.IEquatable<IOverloadApi>, global::TestApi.IOverloadApi.IManagedInterface
    {
        private readonly nint _handle;
        /// <summary>Initializes a new instance of the <see cref = "IOverloadApi"/> struct.</summary>
        /// <param name="handle">A pointer to the unmanaged interface.</param>
        public IOverloadApi(nint handle)
        {
            _handle = handle;
        }

        /// <inheritdoc/>
        public nint Handle => _handle;
        /// <inheritdoc/>
        public readonly bool HasValue => _handle != default;

        /// <inheritdoc/>
        public override int GetHashCode()
        {
            return _handle.GetHashCode();
        }

        /// <inheritdoc/>
        public bool Equals(IOverloadApi other)
        {
            return _handle == other._handle;
        }

        /// <inheritdoc/>
        public override bool Equals(object? other)
        {
            if (_handle == default)
                return other == null;
            if (other == null)
                return false;
            if (other is IOverloadApi otherValue)
            {
                return Equals(otherValue);
            }

            return false;
        }

        /// <summary>Determines whether the specified values are equal.</summary>
        /// <param name="lhs">The value on the left side of the operator.</param>
        /// <param name="rhs">The value on the right side of the operator.</param>
        /// <returns><c>true</c> if the values are equal; otherwise, <c>false</c>.</returns>
        public static bool operator ==(IOverloadApi lhs, object? rhs)
        {
            if (rhs is null)
                return !lhs.HasValue;
            if (rhs is IOverloadApi other)
                return lhs.Equals(other);
            return false;
        }

        /// <summary>Determines whether the specified values are not equal.</summary>
        /// <param name="lhs">The value on the left side of the operator.</param>
        /// <param name="rhs">The value on the right side of the operator.</param>
        /// <returns><c>true</c> if the values are not equal; otherwise, <c>false</c>.</returns>
        public static bool operator !=(IOverloadApi lhs, object? rhs) => !(lhs == rhs);
        public partial int GetValue(int x, int y)
        {
            return __PInvoke(_handle, x, y);
            // Local P/Invoke
            [global::System.Runtime.InteropServices.DllImportAttribute("SampSharp", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl, EntryPoint = "IOverloadApi_getValue2", ExactSpelling = true)]
            static unsafe extern int __PInvoke(nint handle_, int x, int y);
        }

        public partial int GetValue(int x)
        {
            return __PInvoke(_handle, x);
            // Local P/Invoke
            [global::System.Runtime.InteropServices.DllImportAttribute("SampSharp", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl, EntryPoint = "IOverloadApi_getValue", ExactSpelling = true)]
            static unsafe extern int __PInvoke(nint handle_, int x);
        }

        /// <summary>Represents the managed interface implemented by its unmanaged counterpart.</summary>
        public partial interface IManagedInterface : global::SampSharp.OpenMp.Core.IUnmanagedInterface
        {
            public int GetValue(int x, int y);
            public int GetValue(int x);
        }
    }
}