//HintName: ICustomEventHandler.g.cs
// <auto-generated />
namespace TestEvents
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SampSharp.SourceGenerator", "1.0.0.0")]
    public partial interface ICustomEventHandler : global::SampSharp.OpenMp.Core.Api.IEventHandler<ICustomEventHandler>
    {
        static global::SampSharp.OpenMp.Core.Api.IEventHandlerMarshaller<ICustomEventHandler> global::SampSharp.OpenMp.Core.Api.IEventHandler<ICustomEventHandler>.Marshaller => EventHandlerMarshaller.Instance;

        /// <summary>Manages the marshalling of native event handlers for <see cref = "ICustomEventHandler"/>.</summary>
        public class EventHandlerMarshaller : global::SampSharp.OpenMp.Core.Api.EventHandlerMarshaller<ICustomEventHandler>
        {
            /// <summary>Gets the singleton instance of the <see cref = "EventHandlerMarshaller"/>.</summary>
            public static EventHandlerMarshaller Instance { get; } = new();

            private delegate void OnEvent_(int id);
            /// <inheritdoc/>
            protected override (nint, object) Create(ICustomEventHandler handler)
            {
                global::System.Delegate __OnEvent_delegate = (OnEvent_)handler.OnEvent;
                nint __OnEvent_ptr = global::System.Runtime.InteropServices.Marshal.GetFunctionPointerForDelegate(__OnEvent_delegate);
                object[] data = [__OnEvent_delegate];
                nint handle = __PInvoke(__OnEvent_ptr);
                return (handle, data);
                // Local P/Invoke
                [global::System.Runtime.InteropServices.DllImportAttribute("MyLib", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl, EntryPoint = "MyEventHandlerImpl_create", ExactSpelling = true)]
                static unsafe extern nint __PInvoke(nint _OnEvent);
            }

            /// <inheritdoc/>
            protected override void Free(nint handle)
            {
                __PInvoke(handle);
                // Local P/Invoke
                [global::System.Runtime.InteropServices.DllImportAttribute("MyLib", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl, EntryPoint = "MyEventHandlerImpl_delete", ExactSpelling = true)]
                static unsafe extern void __PInvoke(nint ptr);
            }
        }
    }
}