//HintName: IMyEventHandler.g.cs
// <auto-generated />
namespace TestEvents
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SampSharp.SourceGenerator", "1.0.0.0")]
    public partial interface IMyEventHandler : global::SampSharp.OpenMp.Core.Api.IEventHandler<IMyEventHandler>
    {
        static global::SampSharp.OpenMp.Core.Api.IEventHandlerMarshaller<IMyEventHandler> global::SampSharp.OpenMp.Core.Api.IEventHandler<IMyEventHandler>.Marshaller => EventHandlerMarshaller.Instance;

        /// <summary>Manages the marshalling of native event handlers for <see cref = "IMyEventHandler"/>.</summary>
        public class EventHandlerMarshaller : global::SampSharp.OpenMp.Core.Api.EventHandlerMarshaller<IMyEventHandler>
        {
            /// <summary>Gets the singleton instance of the <see cref = "EventHandlerMarshaller"/>.</summary>
            public static EventHandlerMarshaller Instance { get; } = new();

            private delegate global::SampSharp.OpenMp.Core.BlittableBoolean OnSomeEvent_(int id, global::SampSharp.OpenMp.Core.Std.StringView __name_native);
            private delegate void OnOtherEvent_(int value);
            /// <inheritdoc/>
            protected override (nint, object) Create(IMyEventHandler handler)
            {
                global::System.Delegate __OnSomeEvent_delegate = (OnSomeEvent_)((int id, global::SampSharp.OpenMp.Core.Std.StringView __name_native) =>
                {
                    string name = default;
                    bool __retVal = default;
                    global::SampSharp.OpenMp.Core.BlittableBoolean __retVal_native = default;
                    // Unmarshal - Convert native data to managed data.
                    name = global::SampSharp.OpenMp.Core.Std.StringViewMarshaller.NativeToManaged.ConvertToManaged(__name_native);
                    __retVal = handler.OnSomeEvent(id, name);
                    // Marshal - Convert managed data to native data.
                    __retVal_native = global::SampSharp.OpenMp.Core.Std.BooleanMarshaller.ManagedToNative.ConvertToUnmanaged(__retVal);
                    return __retVal_native;
                }), __OnOtherEvent_delegate = (OnOtherEvent_)handler.OnOtherEvent;
                nint __OnSomeEvent_ptr = global::System.Runtime.InteropServices.Marshal.GetFunctionPointerForDelegate(__OnSomeEvent_delegate), __OnOtherEvent_ptr = global::System.Runtime.InteropServices.Marshal.GetFunctionPointerForDelegate(__OnOtherEvent_delegate);
                object[] data = [__OnSomeEvent_delegate, __OnOtherEvent_delegate];
                nint handle = __PInvoke(__OnSomeEvent_ptr, __OnOtherEvent_ptr);
                return (handle, data);
                // Local P/Invoke
                [global::System.Runtime.InteropServices.DllImportAttribute("SampSharp", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl, EntryPoint = "MyEventHandlerImpl_create", ExactSpelling = true)]
                static unsafe extern nint __PInvoke(nint _OnSomeEvent, nint _OnOtherEvent);
            }

            /// <inheritdoc/>
            protected override void Free(nint handle)
            {
                __PInvoke(handle);
                // Local P/Invoke
                [global::System.Runtime.InteropServices.DllImportAttribute("SampSharp", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl, EntryPoint = "MyEventHandlerImpl_delete", ExactSpelling = true)]
                static unsafe extern void __PInvoke(nint ptr);
            }
        }
    }
}