//HintName: IRefOutApi.g.cs
// <auto-generated />
#nullable enable
namespace TestApi
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SampSharp.SourceGenerator", "0.0.0.0")]
    [global::System.Runtime.CompilerServices.SkipLocalsInitAttribute]
    public readonly unsafe partial struct IRefOutApi : global::System.IEquatable<IRefOutApi>, global::TestApi.IRefOutApi.IManagedInterface
    {
        private readonly nint _handle;
        /// <summary>Initializes a new instance of the <see cref = "IRefOutApi"/> struct.</summary>
        /// <param name="handle">A pointer to the unmanaged interface.</param>
        public IRefOutApi(nint handle)
        {
            _handle = handle;
        }

        /// <inheritdoc/>
        public nint Handle => _handle;
        /// <inheritdoc/>
        public readonly bool HasValue => _handle != default;

        /// <inheritdoc/>
        public override int GetHashCode()
        {
            return _handle.GetHashCode();
        }

        /// <inheritdoc/>
        public bool Equals(IRefOutApi other)
        {
            return _handle == other._handle;
        }

        /// <inheritdoc/>
        public override bool Equals(object? other)
        {
            if (_handle == default)
                return other == null;
            if (other == null)
                return false;
            if (other is IRefOutApi otherValue)
            {
                return Equals(otherValue);
            }

            return false;
        }

        /// <summary>Determines whether the specified values are equal.</summary>
        /// <param name="lhs">The value on the left side of the operator.</param>
        /// <param name="rhs">The value on the right side of the operator.</param>
        /// <returns><c>true</c> if the values are equal; otherwise, <c>false</c>.</returns>
        public static bool operator ==(IRefOutApi lhs, object? rhs)
        {
            if (rhs is null)
                return !lhs.HasValue;
            if (rhs is IRefOutApi other)
                return lhs.Equals(other);
            return false;
        }

        /// <summary>Determines whether the specified values are not equal.</summary>
        /// <param name="lhs">The value on the left side of the operator.</param>
        /// <param name="rhs">The value on the right side of the operator.</param>
        /// <returns><c>true</c> if the values are not equal; otherwise, <c>false</c>.</returns>
        public static bool operator !=(IRefOutApi lhs, object? rhs) => !(lhs == rhs);
        public partial void GetValues(out int x, out int y)
        {
            __PInvoke(_handle, out x, out y);
            // Local P/Invoke
            [global::System.Runtime.InteropServices.DllImportAttribute("SampSharp", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl, EntryPoint = "IRefOutApi_getValues", ExactSpelling = true)]
            static unsafe extern void __PInvoke(nint handle_, out int x, out int y);
        }

        public partial void Transform(ref int value)
        {
            __PInvoke(_handle, ref value);
            // Local P/Invoke
            [global::System.Runtime.InteropServices.DllImportAttribute("SampSharp", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl, EntryPoint = "IRefOutApi_transform", ExactSpelling = true)]
            static unsafe extern void __PInvoke(nint handle_, ref int value);
        }

        /// <summary>Represents the managed interface implemented by its unmanaged counterpart.</summary>
        public partial interface IManagedInterface : global::SampSharp.OpenMp.Core.IUnmanagedInterface
        {
            public void GetValues(out int x, out int y);
            public void Transform(ref int value);
        }
    }
}