//HintName: IDerived.g.cs
// <auto-generated />
#nullable enable
namespace TestApi
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SampSharp.SourceGenerator", "0.0.0.0")]
    [global::System.Runtime.CompilerServices.SkipLocalsInitAttribute]
    public readonly unsafe partial struct IDerived : global::System.IEquatable<IDerived>, global::TestApi.IDerived.IManagedInterface, global::TestApi.IBase.IManagedInterface
    {
        private readonly nint _handle;
        /// <summary>Initializes a new instance of the <see cref = "IDerived"/> struct.</summary>
        /// <param name="handle">A pointer to the unmanaged interface.</param>
        public IDerived(nint handle)
        {
            _handle = handle;
        }

        /// <inheritdoc/>
        public nint Handle => _handle;

        /// <summary>Casts the <see cref = "IDerived"/> to a <see cref = "global::TestApi.IBase"/>.</summary>
        /// <param name="value">The <see cref = "IDerived"/> to cast.</param>
        /// <returns>The converted <see cref = "global::TestApi.IBase"/>.</returns>
        public static explicit operator global::TestApi.IBase(IDerived value)
        {
            return new global::TestApi.IBase(value.Handle);
        }

        /// <summary>Casts the <see cref = "global::TestApi.IBase"/> to a <see cref = "IDerived"/>.</summary>
        /// <param name="value">The <see cref = "global::TestApi.IBase"/> to cast.</param>
        /// <returns>The converted <see cref = "IDerived"/>.</returns>
        public static explicit operator IDerived(global::TestApi.IBase value)
        {
            return new IDerived(value.Handle);
        }

        /// <inheritdoc/>
        public readonly bool HasValue => _handle != default;

        /// <inheritdoc/>
        public override int GetHashCode()
        {
            return _handle.GetHashCode();
        }

        /// <inheritdoc/>
        public bool Equals(IDerived other)
        {
            return _handle == other._handle;
        }

        /// <inheritdoc/>
        public override bool Equals(object? other)
        {
            if (_handle == default)
                return other == null;
            if (other == null)
                return false;
            if (other is IDerived otherValue)
            {
                return Equals(otherValue);
            }

            return false;
        }

        /// <summary>Determines whether the specified values are equal.</summary>
        /// <param name="lhs">The value on the left side of the operator.</param>
        /// <param name="rhs">The value on the right side of the operator.</param>
        /// <returns><c>true</c> if the values are equal; otherwise, <c>false</c>.</returns>
        public static bool operator ==(IDerived lhs, object? rhs)
        {
            if (rhs is null)
                return !lhs.HasValue;
            if (rhs is IDerived other)
                return lhs.Equals(other);
            return false;
        }

        /// <summary>Determines whether the specified values are not equal.</summary>
        /// <param name="lhs">The value on the left side of the operator.</param>
        /// <param name="rhs">The value on the right side of the operator.</param>
        /// <returns><c>true</c> if the values are not equal; otherwise, <c>false</c>.</returns>
        public static bool operator !=(IDerived lhs, object? rhs) => !(lhs == rhs);
        public int GetId()
        {
            return ((global::TestApi.IBase)this).GetId();
        }

        public partial string GetName()
        {
            string __retVal = default;
            global::SampSharp.OpenMp.Core.Std.StringView __retVal_native = default;
            {
                __retVal_native = __PInvoke(_handle);
            }

            // Unmarshal - Convert native data to managed data.
            __retVal = global::SampSharp.OpenMp.Core.Std.StringViewMarshaller.NativeToManaged.ConvertToManaged(__retVal_native);
            return __retVal;
            // Local P/Invoke
            [global::System.Runtime.InteropServices.DllImportAttribute("SampSharp", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl, EntryPoint = "IDerived_getName", ExactSpelling = true)]
            static unsafe extern global::SampSharp.OpenMp.Core.Std.StringView __PInvoke(nint handle_);
        }

        /// <summary>Represents the managed interface implemented by its unmanaged counterpart.</summary>
        public partial interface IManagedInterface : global::SampSharp.OpenMp.Core.IUnmanagedInterface
        {
            public string GetName();
        }
    }
}