//HintName: IFunctionApi.g.cs
// <auto-generated />
#nullable enable
namespace TestApi
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SampSharp.SourceGenerator", "0.0.0.0")]
    [global::System.Runtime.CompilerServices.SkipLocalsInitAttribute]
    public readonly unsafe partial struct IFunctionApi : global::System.IEquatable<IFunctionApi>, global::TestApi.IFunctionApi.IManagedInterface
    {
        private readonly nint _handle;
        /// <summary>Initializes a new instance of the <see cref = "IFunctionApi"/> struct.</summary>
        /// <param name="handle">A pointer to the unmanaged interface.</param>
        public IFunctionApi(nint handle)
        {
            _handle = handle;
        }

        /// <inheritdoc/>
        public nint Handle => _handle;
        /// <inheritdoc/>
        public readonly bool HasValue => _handle != default;

        /// <inheritdoc/>
        public override int GetHashCode()
        {
            return _handle.GetHashCode();
        }

        /// <inheritdoc/>
        public bool Equals(IFunctionApi other)
        {
            return _handle == other._handle;
        }

        /// <inheritdoc/>
        public override bool Equals(object? other)
        {
            if (_handle == default)
                return other == null;
            if (other == null)
                return false;
            if (other is IFunctionApi otherValue)
            {
                return Equals(otherValue);
            }

            return false;
        }

        /// <summary>Determines whether the specified values are equal.</summary>
        /// <param name="lhs">The value on the left side of the operator.</param>
        /// <param name="rhs">The value on the right side of the operator.</param>
        /// <returns><c>true</c> if the values are equal; otherwise, <c>false</c>.</returns>
        public static bool operator ==(IFunctionApi lhs, object? rhs)
        {
            if (rhs is null)
                return !lhs.HasValue;
            if (rhs is IFunctionApi other)
                return lhs.Equals(other);
            return false;
        }

        /// <summary>Determines whether the specified values are not equal.</summary>
        /// <param name="lhs">The value on the left side of the operator.</param>
        /// <param name="rhs">The value on the right side of the operator.</param>
        /// <returns><c>true</c> if the values are not equal; otherwise, <c>false</c>.</returns>
        public static bool operator !=(IFunctionApi lhs, object? rhs) => !(lhs == rhs);
        public partial int DoSomething()
        {
            return __PInvoke(_handle);
            // Local P/Invoke
            [global::System.Runtime.InteropServices.DllImportAttribute("SampSharp", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl, EntryPoint = "IFunctionApi_customFunctionName", ExactSpelling = true)]
            static unsafe extern int __PInvoke(nint handle_);
        }

        /// <summary>Represents the managed interface implemented by its unmanaged counterpart.</summary>
        public partial interface IManagedInterface : global::SampSharp.OpenMp.Core.IUnmanagedInterface
        {
            public int DoSomething();
        }
    }
}