//HintName: IBoolEventHandler.g.cs
// <auto-generated />
namespace TestEvents
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SampSharp.SourceGenerator", "1.0.0.0")]
    public partial interface IBoolEventHandler : global::SampSharp.OpenMp.Core.Api.IEventHandler<IBoolEventHandler>
    {
        static global::SampSharp.OpenMp.Core.Api.IEventHandlerMarshaller<IBoolEventHandler> global::SampSharp.OpenMp.Core.Api.IEventHandler<IBoolEventHandler>.Marshaller => EventHandlerMarshaller.Instance;

        /// <summary>Manages the marshalling of native event handlers for <see cref = "IBoolEventHandler"/>.</summary>
        public class EventHandlerMarshaller : global::SampSharp.OpenMp.Core.Api.EventHandlerMarshaller<IBoolEventHandler>
        {
            /// <summary>Gets the singleton instance of the <see cref = "EventHandlerMarshaller"/>.</summary>
            public static EventHandlerMarshaller Instance { get; } = new();

            private delegate global::SampSharp.OpenMp.Core.BlittableBoolean OnToggle_(global::SampSharp.OpenMp.Core.BlittableBoolean __enabled_native, int id);
            /// <inheritdoc/>
            protected override (nint, object) Create(IBoolEventHandler handler)
            {
                global::System.Delegate __OnToggle_delegate = (OnToggle_)((global::SampSharp.OpenMp.Core.BlittableBoolean __enabled_native, int id) =>
                {
                    bool enabled = default;
                    bool __retVal = default;
                    global::SampSharp.OpenMp.Core.BlittableBoolean __retVal_native = default;
                    // Unmarshal - Convert native data to managed data.
                    enabled = global::SampSharp.OpenMp.Core.Std.BooleanMarshaller.NativeToManaged.ConvertToManaged(__enabled_native)!;
                    __retVal = handler.OnToggle(enabled, id);
                    // Marshal - Convert managed data to native data.
                    __retVal_native = global::SampSharp.OpenMp.Core.Std.BooleanMarshaller.ManagedToNative.ConvertToUnmanaged(__retVal);
                    return __retVal_native;
                });
                nint __OnToggle_ptr = global::System.Runtime.InteropServices.Marshal.GetFunctionPointerForDelegate(__OnToggle_delegate);
                object[] data = [__OnToggle_delegate];
                nint handle = __PInvoke(__OnToggle_ptr);
                return (handle, data);
                // Local P/Invoke
                [global::System.Runtime.InteropServices.DllImportAttribute("SampSharp", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl, EntryPoint = "BoolEventHandlerImpl_create", ExactSpelling = true)]
                static unsafe extern nint __PInvoke(nint _OnToggle);
            }

            /// <inheritdoc/>
            protected override void Free(nint handle)
            {
                __PInvoke(handle);
                // Local P/Invoke
                [global::System.Runtime.InteropServices.DllImportAttribute("SampSharp", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl, EntryPoint = "BoolEventHandlerImpl_delete", ExactSpelling = true)]
                static unsafe extern void __PInvoke(nint ptr);
            }
        }
    }
}