//HintName: IPartialApi.g.cs
// <auto-generated />
#nullable enable
namespace TestApi
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SampSharp.SourceGenerator", "1.0.0.0")]
    [global::System.Runtime.CompilerServices.SkipLocalsInitAttribute]
    public readonly unsafe partial struct IPartialApi : global::System.IEquatable<IPartialApi>, global::SampSharp.OpenMp.Core.IUnmanagedInterface
    {
        private readonly nint _handle;
        /// <summary>Initializes a new instance of the <see cref = "IPartialApi"/> struct.</summary>
        /// <param name="handle">A pointer to the unmanaged interface.</param>
        public IPartialApi(nint handle)
        {
            _handle = handle;
        }

        /// <inheritdoc/>
        public nint Handle => _handle;
        /// <inheritdoc/>
        public readonly bool HasValue => _handle != default;

        /// <inheritdoc/>
        public override int GetHashCode()
        {
            return _handle.GetHashCode();
        }

        /// <inheritdoc/>
        public bool Equals(IPartialApi other)
        {
            return _handle == other._handle;
        }

        /// <inheritdoc/>
        public override bool Equals(object? other)
        {
            if (_handle == default)
                return other == null;
            if (other == null)
                return false;
            if (other is IPartialApi otherValue)
            {
                return Equals(otherValue);
            }

            return false;
        }

        /// <summary>Determines whether the specified values are equal.</summary>
        /// <param name="lhs">The value on the left side of the operator.</param>
        /// <param name="rhs">The value on the right side of the operator.</param>
        /// <returns><c>true</c> if the values are equal; otherwise, <c>false</c>.</returns>
        public static bool operator ==(IPartialApi lhs, object? rhs)
        {
            if (rhs is null)
                return !lhs.HasValue;
            if (rhs is IPartialApi other)
                return lhs.Equals(other);
            return false;
        }

        /// <summary>Determines whether the specified values are not equal.</summary>
        /// <param name="lhs">The value on the left side of the operator.</param>
        /// <param name="rhs">The value on the right side of the operator.</param>
        /// <returns><c>true</c> if the values are not equal; otherwise, <c>false</c>.</returns>
        public static bool operator !=(IPartialApi lhs, object? rhs) => !(lhs == rhs);
        public partial int GetComponentType()
        {
            return __PInvoke(_handle);
            // Local P/Invoke
            [global::System.Runtime.InteropServices.DllImportAttribute("SampSharp", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl, EntryPoint = "IPartialApi_getComponentType", ExactSpelling = true)]
            static unsafe extern int __PInvoke(nint handle_);
        }

        public partial string GetName()
        {
            string __retVal = default;
            global::SampSharp.OpenMp.Core.Std.StringView __retVal_native = default;
            {
                __retVal_native = __PInvoke(_handle);
            }

            // Unmarshal - Convert native data to managed data.
            __retVal = global::SampSharp.OpenMp.Core.Std.StringViewMarshaller.NativeToManaged.ConvertToManaged(__retVal_native);
            return __retVal;
            // Local P/Invoke
            [global::System.Runtime.InteropServices.DllImportAttribute("SampSharp", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl, EntryPoint = "IPartialApi_getName", ExactSpelling = true)]
            static unsafe extern global::SampSharp.OpenMp.Core.Std.StringView __PInvoke(nint handle_);
        }

        /// <summary>Represents the managed interface implemented by its unmanaged counterpart.</summary>
        public partial interface IManagedInterface : global::SampSharp.OpenMp.Core.IUnmanagedInterface
        {
            public int GetComponentType();
            public string GetName();
        }
    }
}