//HintName: IDerivedEventHandler.g.cs
// <auto-generated />
namespace TestEvents
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SampSharp.SourceGenerator", "0.0.0.0")]
    public partial interface IDerivedEventHandler : global::SampSharp.OpenMp.Core.Api.IEventHandler<IDerivedEventHandler>
    {
        static global::SampSharp.OpenMp.Core.Api.IEventHandlerMarshaller<IDerivedEventHandler> global::SampSharp.OpenMp.Core.Api.IEventHandler<IDerivedEventHandler>.Marshaller => EventHandlerMarshaller.Instance;

        /// <summary>Manages the marshalling of native event handlers for <see cref = "IDerivedEventHandler"/>.</summary>
        public class EventHandlerMarshaller : global::SampSharp.OpenMp.Core.Api.EventHandlerMarshaller<IDerivedEventHandler>
        {
            /// <summary>Gets the singleton instance of the <see cref = "EventHandlerMarshaller"/>.</summary>
            public static EventHandlerMarshaller Instance { get; } = new();

            private delegate global::SampSharp.OpenMp.Core.BlittableBoolean OnDerivedEvent_(global::SampSharp.OpenMp.Core.Std.StringView __name_native);
            private delegate void OnBaseEvent_(int id);
            /// <inheritdoc/>
            protected override (nint, object) Create(IDerivedEventHandler handler)
            {
                global::System.Delegate __OnDerivedEvent_delegate = (OnDerivedEvent_)((global::SampSharp.OpenMp.Core.Std.StringView __name_native) =>
                {
                    string name = default;
                    bool __retVal = default;
                    global::SampSharp.OpenMp.Core.BlittableBoolean __retVal_native = default;
                    // Unmarshal - Convert native data to managed data.
                    name = global::SampSharp.OpenMp.Core.Std.StringViewMarshaller.NativeToManaged.ConvertToManaged(__name_native);
                    __retVal = handler.OnDerivedEvent(name);
                    // Marshal - Convert managed data to native data.
                    __retVal_native = global::SampSharp.OpenMp.Core.Std.BooleanMarshaller.ManagedToNative.ConvertToUnmanaged(__retVal);
                    return __retVal_native;
                }), __OnBaseEvent_delegate = (OnBaseEvent_)handler.OnBaseEvent;
                nint __OnDerivedEvent_ptr = global::System.Runtime.InteropServices.Marshal.GetFunctionPointerForDelegate(__OnDerivedEvent_delegate), __OnBaseEvent_ptr = global::System.Runtime.InteropServices.Marshal.GetFunctionPointerForDelegate(__OnBaseEvent_delegate);
                object[] data = [__OnDerivedEvent_delegate, __OnBaseEvent_delegate];
                nint handle = __PInvoke(__OnDerivedEvent_ptr, __OnBaseEvent_ptr);
                return (handle, data);
                // Local P/Invoke
                [global::System.Runtime.InteropServices.DllImportAttribute("SampSharp", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl, EntryPoint = "DerivedEventHandlerImpl_create", ExactSpelling = true)]
                static unsafe extern nint __PInvoke(nint _OnDerivedEvent, nint _OnBaseEvent);
            }

            /// <inheritdoc/>
            protected override void Free(nint handle)
            {
                __PInvoke(handle);
                // Local P/Invoke
                [global::System.Runtime.InteropServices.DllImportAttribute("SampSharp", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl, EntryPoint = "DerivedEventHandlerImpl_delete", ExactSpelling = true)]
                static unsafe extern void __PInvoke(nint ptr);
            }
        }
    }
}