name: CI - Component x64 (Linux)

on:
  push:
    branches:
      - master
      - release/1.*
    paths:
      - .github/workflows/component-linux.yml
      - src/sampsharp-component/**
      - external/**
      - build.sh
  
  pull_request:
    branches:
      - master
      - release/1.*
    paths:
      - .github/workflows/component-linux.yml
      - src/sampsharp-component/**
      - external/**
      - build.sh

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y gcc g++ cmake

      - name: Build component
        run: ./build.sh component publish

      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: sampsharp-component-linux
          path: build/artifacts/sampsharp-component/
          if-no-files-found: error
