name: CI - Component Libraries

on:
  push:
    branches:
      - main
      - release/1.*
    paths:
      - .github/workflows/dotnet-component.yml
      - src/SampSharp.*/**
      - test/TestMode.*/**
      - SampSharp.slnx
      - Directory.Build.props
      - build.sh

  pull_request:
    branches:
      - main
      - release/1.*
    paths:
      - .github/workflows/dotnet-component.yml
      - src/SampSharp.*/**
      - test/TestMode.*/**
      - SampSharp.slnx
      - Directory.Build.props
      - build.sh

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6

    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: '10.0.x'

    - name: Build component libraries
      run: ./build.sh component-libraries

    - name: Pack component libraries
      run: ./build.sh component-libraries publish

    - name: Upload NuGet packages
      uses: actions/upload-artifact@v7
      with:
        name: sampsharp-component-nuget-packages
        path: build/artifacts/packages/
        if-no-files-found: error
