name: Plugin (Linux)

on:
  push:
    branches: [ master ]
    paths:
      - .github/workflows/plugin-linux.yml
      - src/SampSharp/**
      - Makefile

  pull_request:
    branches: [ master ]
    paths:
      - .github/workflows/plugin-linux.yml
      - src/SampSharp/**
      - Makefile

  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install deps
        run: |
          sudo apt-get update -y -qq
          sudo apt-get upgrade -y -qq gcc g++
          sudo apt-get install -y -qq gcc-multilib g++-multilib
          gcc --version
          g++ --version
        
      - name: Build plugin
        run: make

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: plugin-bin
          path: bin/
